name: Build and Deploy to Netlify

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.11.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci
      - run: npm install babel-eslint --save-dev
      - run: npm run lint
      - run: npm test
      - name: Install Netlify CLI
        run: npm install netlify-cli -g
      - name: Build site
        run: npm run build
      - name: Deploy to Netlify
        run: netlify deploy --prod --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=./public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
